spring:
  datasource:
    url: jdbc:h2:mem:wexprepag
    driverClassName: org.h2.Driver
    username: app
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2

  jackson:
    default-property-inclusion: non-null
server:
  port: 8081