create table cartao (
	numero varchar(255) not null,
	nome varchar(255),
	saldo decimal(19,2),
	senha varchar(255),
	validade date,
	primary key (numero)
);
    
create table venda (
	id bigint generated by default as identity,
	data timestamp,
	estabelecimento varchar(255),
	saldo_anterior decimal(19,2),
	valor decimal(19,2),
	cartao_numero varchar(255),
	primary key (id)
);

alter table venda add constraint fk_venda_cartao foreign key (cartao_numero) references cartao;
